#################################
# General setup
#################################
language: python

sudo: false

#addons:
#  apt:
#    packages:
#    - dpkg-dev
#    - build-essential
#    - libwebkitgtk-dev
#    - libjpeg-dev
#    - libtiff4-dev
#    - libgtk2.0-dev
#    - libsdl1.2-dev
#    - libgstreamer-plugins-base0.10-dev
#    - libnotify-dev
#    - freeglut3
#    - freeglut3-dev

matrix:
  include:
#  - python: "2.7"
#    env:
#      # wxPython_Phoenix-3.0.3-dev1956+aab2833 with fixes
#      - WXPYTHON=https://gitlab.com/dougthor42/wxPython_Phoenix-wheels/raw/master/ubuntu-12.04.5-desktop-amd64/wxPython_Phoenix-3.0.3.dev1956_aab2833-cp27-cp27mu-linux_x86_64.whl
  - python: "3.4"
    env:
      # wxPython_Phoenix-3.0.3-dev1956+aab2833 with fixes
      - WXPYTHON=https://gitlab.com/dougthor42/wxPython_Phoenix-wheels/raw/master/ubuntu-15.10-server-amd64/wxPython_Phoenix-3.0.3.dev1956+aab2833-cp34-cp34m-linux_x86_64.whl

notifications:
  email: false

#################################
# Build Lifecycle
#################################
before_install:
  - echo "----- before_install -----"

install:
  - echo "----- install -----"

  # Start the install of everything
  - pip install --upgrade pip
  - "pip install --pre --only-binary :all: -f https://wxpython.org/Phoenix/snapshot-builds/ wxPython_Phoenix"
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt
#  - pip install $WXPYTHON

script:
  - echo "----- script -----"
  - green wafer_map -vvv --run-coverage

after_success:
  - echo "----- after_success -----"

  # Send coverage information to coveralls.io
  - coveralls
