### ----------------------
### General Configuration
### ----------------------

environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"
      WXPYTHON: http://dougthor42.github.io/tools/wxPython_Phoenix-3.0.3.dev1956-cp27-cp27m-win32.whl

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "64"
      WXPYTHON: http://dougthor42.github.io/tools/wxPython_Phoenix-3.0.3.dev1956-cp27-cp27m-win_amd64.whl

#    - PYTHON: "C:\\Python33"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "32"
#
#    - PYTHON: "C:\\Python33-x64"
#      PYTHON_VERSION: "3.3.5"
#      PYTHON_ARCH: "64"

#   - PYTHON: "C:\\Python34"
#     PYTHON_VERSION: "3.4.1"
#     PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_VERSION: "3.4.3"
      PYTHON_ARCH: "64"
      DISTUTILS_USE_SDK: "1"
      WXPYTHON: http://dougthor42.github.io/tools/wxPython_Phoenix-3.0.3.dev1956-cp34-cp34m-win_amd64.whl

install:
  # Check that we have the expected version and architecture for Python
  - "%PYTHON%\\python.exe --version"

  # install dependencies
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install %WXPYTHON%"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"

build: off  # Not a C# project, build stuff at the test step instead.

test_script:
  # Build the compiled extension and run the project tests
  - "%PYTHON%\\python.exe --version"
  - "%PYTHON%\\python.exe -m green -vvv wafer_map"

#after_test:
  # if tests OK, create whl package
#  - "%CMD_IN_ENV% python setup.py sdist bdist_wheel"

#artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
#  - path: dist\*.whl

